site_name: 'L5: A Processing Library in Lua'
site_url: https://l5lua.org
validation:
  absolute_links: ignore
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
theme:
  name: material
  palette:
    primary: gold
    accent: blue
  logo: assets/L5-logo-blob.png
  font: false
  favicon: assets/L5-logo-blob.png
  features:
    - navigation.tracking # URL address bar
    - navigation.prune # Render only visible navigation
    - navigation.path # Breadcrumbs for beginning of filename
    - toc.follow # Follow navigation
    - toc.integrate # rendering nav bar to the left
    - content.code.copy # Copy button
    - content.code.select # Allow selecting code
  custom_dir: overrides
  static_templates:
    - 404.html
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
# Added for collapsible tabs for installations
markdown_extensions:
  - toc:
      toc_depth: 3
nav:
  - Home: index.md
  - Getting Started: download/index.md
  - Learn:
      - Tutorials: tutorials/index.md
      - Examples: examples/index.md
      - L5 for Processing-p5.js programmers: L5-for-processingp5.md
  - Reference:
      - Reference Summary: reference/index.md
      - Shape: reference/#shape
      - Color: reference/#color
      - Typography: reference/#typography
      - Image: reference/#image
      - Media: reference/#media
      - Transform: reference/#transform
      - Environment: reference/#environment
      - Rendering: reference/#rendering
      - Math: reference/#math
      - IO: reference/#io
      - Events: reference/#events
      - Data: reference/#data
      - Structure: reference/#structure
      - Constants: reference/#constants
      - Foundation: reference/#foundation
  - Contributing:
      - How To: contributing.md
      - Forum: https://discourse.processing.org/c/l5/
      - Bug Reports: bug-reports.md
  - Blog: https://notapipe.itch.io/l5/devlog
  - About:
      - For developers: how.md
      - Copyleft: copyleft.md
